# local用コンテナイメージ作成用
version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app-div:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    ## ↓ 開発用にpumaを起動させない#####
    # command: /bin/bash
    # tty: true
    # stdin_open: true
    ####################################
    depends_on:
     - db
  web-div:
    build:
      context: ./nginx
      dockerfile: Dockerfile-div
    ports:
      - 80:80
    depends_on:
      - app-div