# メモ 
# localでの実行コマンド => circleci config validate
version: 2.1 # circleciのversion

orbs:  # orbsを定義
  ruby: circleci/ruby@1.4.0
  node: circleci/node@2
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

workflows:
  build_test_deploy: # ワークフロー名
    jobs:            # 実行ジョブのリスト定義
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true # ECRにリポジトリがなかったら創る
          region: $AWS_REGION
          registry-id: AWS_ECR_REGISTRY_ID
          executor: aws-ecr/default
          remote-docker-layer-caching: true
          repo: some_one_letter_app # ECRのリポジトリ
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update: #
          requires:
            - aws-ecr/build-and-push-image
          family: 'SomeOneLetter-task-define' # ECSのタスク定義名
          cluster: 'SOL-2'                    # ECSのクラスター名かARNのフルパス
          service-name: 'SOL-2-service'              # サービス名
          container-image-name-updates: "container=app,tag=${CIRCLE_SHA1}"